### ISSUE TITLE
Integration with recommender packages

### ISSUE THREAD

**Issue by maciejkula** [zygmuntz/goodbooks-10k#1]
I maintain a bunch of recommender packages, and this dataset could be super useful for my users!

Would you be willing to integrate this into [LightFM](https://github.com/lyst/lightfm) or [Spotlight](https://github.com/maciejkula/spotlight)? (As in, make it easily downloadable and so on.)

**Comment by zygmuntz** [comment]
Sure thing! What do you need from me?

**Comment by maciejkula** [comment]
I would write all the code on my end, but I was wondering if you'd be up to do some more data packaging. 

For bandwidth and speed of loading, I use [h5py](http://www.h5py.org/) files for my datasets. Would you be willing to re-package the data in that format, and maybe include them as Github release files? (Something along the lines of the downloads [here](https://github.com/maciejkula/recommender_datasets/releases)).

**Comment by zygmuntz** [comment]
That's a good idea, I will make a release. Please send me some example code for packing CSV into HDF5.

**Comment by maciejkula** [comment]
Awesome!

I have some code [here](https://github.com/maciejkula/recommender_datasets/blob/master/recommender_datasets/output.py#L61) (warning, not end-user code, might be fairly horrible). It basically boils down to stuffing numpy arrays into the file with the appropriate names.

**Comment by zygmuntz** [comment]
I made a release: https://github.com/zygmuntz/goodbooks-10k/releases/tag/v1.0

As regards HDF5, I created a file with integer-only data: ratings, to_read and book_tags. Books and tags contain numbers mixed with strings so I skipped them.

**Comment by maciejkula** [comment]
Great, I'll have a look soon and let you know how I get on.

**Comment by zygmuntz** [comment]
Closing upon successful completion (https://github.com/maciejkula/spotlight/pull/62).
