### ISSUE TITLE
Error in ratingmat[current_user, ] : subscript out of bounds

### ISSUE THREAD

**Issue by ran88dom99** [zygmuntz/goodbooks-10k#5]
Please help I get error:

```{r}
current_user &lt;- "7329"
str(ratingmat)
rated_items &lt;- which(!is.na((as.data.frame(ratingmat[current_user, ]))))
selected_users &lt;- names(which(apply(!is.na(ratingmat[ ,rated_items]), 1, sum) &gt;= 2))
head(selected_users, 40)
```

Error in ratingmat[current_user, ] : subscript out of bounds

**Comment by ran88dom99** [comment]
simply changing current_user to "8" makes this part run.  Because its the first row name and neither 7329 nor 17329 exist in row names. that 7329 is dependent on random seed but no numbers go above summary(as.integer(rownames(ratingmat))) 10000

**Comment by ran88dom99** [comment]
glimpse(ratingmat)
summary(as.integer(ratingmat@Dimnames$user_id))
 Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      8   13427   26638   26841   40486   53407 

What was I supposed to do? Is there some setting I could change? BUT

> any( (ratingmat@Dimnames$user_id)=="17329")
[1] FALSE
> any( as.integer(ratingmat@Dimnames$user_id)==17329)
FALSE

**Comment by ran88dom99** [comment]
BUT THEN max(users==17329), even any(sample_users==17329) =1
perhaps you intended to use base::as.matrix instead of Matrix::as.matrix?

**Comment by zygmuntz** [comment]
Please contact Philipp Spachtholz, the author of the R notebook, for help with this.
